version: "3.8"

services:
  api:
    build:
      context: ./api-go
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - lab-network
    depends_on:
      - keycloak

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - lab-network
    depends_on:
      - api

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    networks:
      - lab-network
    command:
      - "start-dev"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge